Repository UAH-ACM/website, pull requests merged in 2021-11, with the labels that each got.

#17 Beta
  members/salwajeries/headshot-3.jpg
  members/salwajeries/index.html
  members/salwajeries/mystyle.css
Labels: One Month Submission, hacktoberfest-accepted

#18 Automatic Site Deployment
  .github/workflows/main.yml
Labels: enhancement, One Month Submission, hacktoberfest-accepted

#19 Hayden onemonth
  members/haydenestes/assets/hayden-modified.png
  members/haydenestes/assets/resume.pdf
  members/haydenestes/css/style.css
  members/haydenestes/css/style.css~
  members/haydenestes/index.html
Labels: One Month Submission, hacktoberfest-accepted

#16 Lane PR
  members/phillane/assets/secondorder.pdf
  members/phillane/index.html
  members/phillane/pbrain.js
  members/phillane/philsite.css
  members/philliplane/assets/000143819.webp
  members/philliplane/assets/Among Us Trap Remix Bass Boosted Leonz.mp3
  members/philliplane/css/style.css
  members/philliplane/index.html
Labels: One Month Submission, hacktoberfest-accepted

#21 Downgrading Deploy Action to prevent issues when renaming or deleting folders
  .github/workflows/main.yml
Labels: bug

#20 added my website
  members/LuisLazcanoTorres/CSS/homeStyle.css
  members/LuisLazcanoTorres/CSS/style.css
  members/LuisLazcanoTorres/Javascript/memeGen.js
  members/LuisLazcanoTorres/assets/0.png
  members/LuisLazcanoTorres/assets/1.png
  members/LuisLazcanoTorres/assets/10.png
  members/LuisLazcanoTorres/assets/11.png
  members/LuisLazcanoTorres/assets/2.png
  members/LuisLazcanoTorres/assets/3.png
  members/LuisLazcanoTorres/assets/4.png
  members/LuisLazcanoTorres/assets/5.png
  members/LuisLazcanoTorres/assets/6.png
  members/LuisLazcanoTorres/assets/7.png
  members/LuisLazcanoTorres/assets/8.png
  members/LuisLazcanoTorres/assets/9.png
  members/LuisLazcanoTorres/assets/LuisLazcanoResume.pdf
  members/LuisLazcanoTorres/assets/Luis_Lazcano_Torres.png
  members/LuisLazcanoTorres/index.html
  members/LuisLazcanoTorres/memes.html
Labels: One Month Submission, hacktoberfest-accepted
